name: Lint Go Code

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Install GO
        uses: actions/setup-go@v2
        with:
            stable: 'false'
            go-version: 1.14

      - name: Run Linting
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.27