name: Lint Go Code

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
            stable: 'false'
            go-version: 1.14

      - name: lint
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          # version of golangci-lint to use in form of v1.2.3
          version: v1.27